formula/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls', namespace='page')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

page/urls.py
from django.urls import path, include
from .views import HomePage, programm

app_name = 'page'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('result/', programm, name='result'),
]

page/models.py
from django.db import models

# Create your models here.

page/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
import matplotlib.pyplot as plt
import numpy as np
from math import sin
from io import BytesIO
import base64
from numpy import sin
import re


class HomePage(TemplateView):
    template_name = 'base.html'

def programm(request):
    fig, ax = plt.subplots()
    ax.set_xlim((-5, 5))
    ax.set_ylim((-5, 5))
    ax.set_aspect("equal")
    ax.grid()
    ax.set_title("Заголовок")
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    x = np.linspace(-5, 5, 100)
    #formy = request.GET['y']
    #g = re.findall('(\d+)', formy)
    #g = ', '.join(g)
    y = eval(request.GET['y'])
    #y = eval('sin(x*' + g + ')')
    ax.plot(x, y)

    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    buffer.seek(0)
    image_png = buffer.getvalue()
    buffer.close()

    graphic = base64.b64encode(image_png)
    graphic = graphic.decode('utf-8')

    return render(request, 'programm.html', {'graphic': graphic})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>График</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<div id="container">
	<div id="header"></div>

	<div id="navigation">
		<div style="margin-left: auto; margin-right: auto; margin-top: 2%; width: 95%;" id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
		  <div class="carousel-inner">
			<div class="carousel-item active">
			  <img src="{% static 'img/1.jpg' %}" class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
			  <img src="{% static 'img/2.jpg' %}" class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
			  <img src="{% static 'img/3.jpg' %}" class="d-block w-100" alt="...">
			</div>
		  </div>
		  <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		  </a>
		  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		  </a>
		</div>
	</div>



	<div id="content" >
		<form action="{% url 'page:result' %}" method="GET">
		  <fieldset>
			<legend></legend>
			<h1 style="color: white; margin-right: 300px;"><label for="formula">Введите формулу: </label></h1>
				<div class="input">
					<input style="width: 300px; height: 40px" type="text" name="y" id="formula">
				</div>

		  </fieldset>
            <input style="width:400px; height: 50px; margin-top: 50px;" type="submit" class="btn btn-outline-light">
		</form>







		<!--<div style="margin-top: 20px;">
			<!-- Подключаем JQuery и Chart.js -->
			<!--<script type="text/javascript"
			 src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
			<script type="text/javascript"
			 src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>-->

			<!-- Готовим контейнер для диаграммы -->
			<!--<div id="content" align="center">
			 <canvas id="myChart" width="628" height="400"></canvas>
			</div>

			<script type="text/javascript">
			 //Готовим диаграмму
			 function Diagram () {
			  var ctx = document.getElementById("myChart");
			  var myChart = new Chart (ctx, {
			   type: 'line',
			   data: {
				labels: [], //Подписи оси x
				datasets: [
				 {
				  label: 'f(x)', //Метка
				  data: [], //Данные
				  borderColor: 'yellow', //Цвет
				  borderWidth: 2, //Толщина линии
				  fill: false //Не заполнять под графиком
				 }
				 //Можно добавить другие графики
				]
			   },
			   options: {
				responsive: false, //Вписывать в размер canvas
				scales: {
				 xAxes: [{
				  display: true
				 }],
				 yAxes: [{
				  display: true
				 }]
				}
			   }
			  });
			  //Заполняем данными
			  for (var x = 0.0; x<=2*Math.PI; x+=Math.PI/10) {
			   myChart.data.labels.push(''+x.toFixed(2));
			   myChart.data.datasets[0].data.push(f(x).toFixed(2));
			  }
			  //Обновляем
			  myChart.update();

			  function f(x) { //Вычисление нужной функции
			   return Math.sqrt(x);
			  }
			 }

			 //Ставим загрузку диаграммы на событие загрузки страницы
			 window.addEventListener("load", Diagram);
			</script>
			<noscript>
			 <div align="center">
			  Извините, для работы приложения нужен включённый Javascript
			 </div>
			</noscript>
		</div>-->
	</div>


	<div id="clear">

	</div>

	<div id="footer">
	<h2>footer (низ сайта)</h2>
	</div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

templates/programm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<img src="data:image/png;base64,{{ graphic|safe }}">
</body>
</html>